services:
  caddy:
    build: ./web
    container_name: whoami-caddy
    restart: unless-stopped
    ports:
      - "${HTTP_IP_BIND:-8080}:80"
    environment:
      - IPV4_HOST=${IPV4_HOST}
      - IPV6_HOST=${IPV6_HOST}
      - MAIN_HOST=${MAIN_HOST}
    volumes:
      - ./web/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        - MAXMIND_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
        - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
    restart: unless-stopped
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DNS_ZONE=${DNS_ZONE:-dns.whoami.local}
      - IPV4_HOST=${IPV4_HOST}
      - IPV6_HOST=${IPV6_HOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_DOCS=${ENABLE_DOCS}
    depends_on:
      - redis

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "${DNS_PORT:-5353}:53/udp" # host 5353 -> contenedor 53/udp
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DNS_ZONE=${DNS_ZONE:-dns-leak.host.com}
      - ANSWER_IP=${ANSWER_IP:-127.0.0.1}
      - DNS_PORT=53 # dentro del contenedor escucha en 53
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./dns:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

volumes:
  caddy_data:
  caddy_config:
