FROM python:3.14-slim
LABEL org.opencontainers.image.source="https://github.com/50512/whoami-diagnostic"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

ENV UV_PROJECT_ENVIRONMENT=/opt/venv \
    PATH=/opt/venv/bin:$PATH \
    UV_COMPILE_BYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync
COPY . .

EXPOSE 53/udp
CMD ["watchfiles", "python -m dns_server", "/app"]
